books/urls.py
from django.urls import path
from books import views

app_name = 'books'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/create/', views.AuthorCreateView.as_view(), name='create_author'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='view_author'),
    path('authors/<int:pk>/books/edit', views.AuthorBooksUpdateView.as_view(), name='update_authorbooks'),
]

inline_forms_books_authors/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
]

books/models.py
from django.db import models
from django.urls import reverse

class Author(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books:view_author', kwargs={'pk': self.pk})


class Book(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    author = models.ForeignKey('Author', null=False, blank=False,
                on_delete=models.CASCADE, related_name='books')

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from books.models import Author, Book



AuthorBooksFormSet = inlineformset_factory(Author, Book, fields=('title', ))

books/views.py
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import (TemplateView, ListView, CreateView, DetailView, FormView)
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect

from books.models import Book, Author
from books.forms import AuthorBooksFormSet


class HomeView(TemplateView):
    template_name = 'home.html'


class AuthorListView(ListView):
    model = Author
    template_name = 'authors.html'


class AuthorCreateView(CreateView):
    model = Author
    template_name = 'create_author.html'
    fields = ['name', ]

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'The author has been created')
        return super().form_valid(form)


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'view_author.html'


class AuthorBooksUpdateView(SingleObjectMixin, FormView):
    model = Author
    template_name = 'update_authorbooks.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Author.objects.all()) # method of SingleObjectMixin
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Author.objects.all()) # method of SingleObjectMixin
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return AuthorBooksFormSet(**self.get_form_kwargs(), instance=self.object)

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.SUCCESS, 'Changes were save')
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('books:view_author', kwargs={'pk':self.object.pk})

books/templates/authors.html
{% extends "base.html" %}


{% block title %} | Authors {% endblock %}

{% block content %}
  <h3 class="h3">Authors</h3>
  {% if author_list %}
    <ul class="list-group">
      {% for author in author_list %}
        <li class="list-group-item">
          <a class="text-reset" href="{{author.get_absolute_url}}">{{ author.name }}</a>
        </li>
      {% endfor %}
    </ul>

  {% else %}

  <p>There are no authors to display</p>

  {% endif %}

  <p class="pt-2">
    <a href="{% url 'books:home' %}" role="button" class="btn btn-secondary w-100">Back</a>
  </p>

{% endblock %}

books/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title> Book App {% block title %} {% endblock %}  </title>
  </head>
  <body>
    <main>
      <div class="container-fluid">
        <div class="d-flex align-items-center py-5">
          <div class="col-12 col-md-6 col-lg-4 mx-auto">
            {% block content %} {% endblock %}
          </div>
        </div>
      </div>
    </main>

  </body>
</html>

books/templates/create_author.html
{% extends "base.html" %}


{% block title %} | Create a new author  {% endblock %}


{% block content %}

<h3>Create author</h3>
<form class="" method="post">

    {% for hidden_field in form.hidden_fields  %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.non_form_erros }}

    {% for field in form %}
      {{ field.errors }}
      {{ field.label_tag }} {{ field }}
    {% endfor %}

    <p class="pt-2">
      <button href="{% url 'books:home' %}" type="submit" value="Add author" class="btn btn-primary w-100 mb-2">Add author</button>
    </p>

</form>


{% endblock %}

books/templates/home.html
{% extends "base.html" %}

{% block title %} | Homepage{% endblock %}

{% block content %}
  <h3>BookStore  Collections</h3>
  <a href="{% url 'books:authors' %}" role="button" class="btn btn-primary w-100 mb-2">All collections</a>
  <a href="{% url 'books:create_author' %}" role="button" class="btn btn-secondary w-100">Add collection</a>


{% endblock %}

books/templates/update_authorbooks.html
{% extends "base.html" %}


{% block title %}  |   Editing books for {{ author.name }} {% endblock %}

{% block content %}

<form class="" method="post" enctype="multipart/form-data">

  {% for hidden_field in form.hidden_fields  %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  {% csrf_token %}

  {{ form.management_form }}
  {{ form.non_form_erros }}

  <h3>Update collections</h3>

  {% for book_form in form.forms %}
  <hr>
  <h5>
    {% if book_form.instance.id %}
      Book: {{ book_form.instance.title|title }}
    {% else %}
      {% if form.forms|length > 1 %}
        Add another book
      {% else %}
        Add a book
      {% endif %}
    {% endif %}
  </h5>
  {% for hidden_field in form.hidden_fields  %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}
  <table>
    {{ book_form.as_table }}
  </table>

  {% endfor %}
  <hr>
  <button type="submit" value="Update collection" class="btn btn-primary w-100 mb-2">Update collections</button>
  <a href="{% url 'books:view_author' author.pk %}" role="button" class="btn btn-secondary w-100">Cancel</a>

</form>


{% endblock %}

books/templates/view_author.html
{% extends "base.html" %}


{% block title %} | {{ author.name }}  {% endblock %}


{% block content %}

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
        <li>{{ message }}</li>
    {% endfor %}

  </ul>
{% endif %}

<h3> Authors Books Details </h3>
<div class="d-flex d-flex-inline"> <span class="pe-2">Authors name: </span> <h5>{{ author.name|title }}</h5> </div>
<hr>

{% for book in author.books.all %}
<div class="small"> Book ID: {{ book.id }} </div>
<div > Title: {{ book.title }} </div>
<hr>
{% endfor %}
<p>
<a role="button" href="{% url 'books:update_authorbooks' pk=author.pk %}" class="btn btn-primary w-100 mb-2">Edit authors books</a>
<a role="button" href="{% url 'books:authors' %}" class="btn btn-secondary w-100">All collections</a>
</p>


{% endblock %}